# Static configuration

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/dynamic.yml

experimental:
  plugins:
    gatewayflowcontroller:
      moduleName: "github.com/RSS3-Network/gatewayflowcontroller"
      version: "v0.0.5"
