upstreams:
  - id: 484052551486931658
    nodes:
      - host: httpany
        port: 8080
        weight: 1
    timeout:
      connect: 6
      send: 6
      read: 6
    type: roundrobin
    scheme: http
    pass_host: pass
    name: httpany
    desc: HTTP Any
    keepalive_pool:
      idle_timeout: 60
      requests: 1000
      size: 320

services:
  -
    id: 1
    upstream_id: 484052551486931658

routes:
  - uri: /data/*
    name: data-route-demo
    desc: Data Route Demo
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD
      - OPTIONS
      - CONNECT
      - TRACE
      - PURGE
    plugins:
      key-auth:
        _meta:
          disable: false
        header: X-API-Key
      proxy-rewrite:
        regex_uri:
          - /data/(.+)
          - /$1
    service_id: 1

plugins:
  - name: "core-logger"
    _meta:
      disable: false
    brokers:
      - host: redpanda-0
        port: 9092
    include_req_body: true
    kafka_topic: apisix
    log_format:
      '@timestamp': $time_iso8601
      client_ip: $remote_addr
      consumer: $consumer_name
      host: $host
      status: $status
      uri: $uri
    meta_refresh_interval: 10
#END
